CREATE TABLE user_profile (
    "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    "profile_picture" TEXT,
    "genre_like" TEXT,
    "actor" TEXT,
    "user_id" INTEGER REFERENCES users(id) on DELETE CASCADE NOT NULL,
    "date_created" TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL
);